site_name: "PhaseNet"
site_description: 'PhaseNet: a deep-neural-network-based seismic arrival-time picking method'
site_author: 'Weiqiang Zhu'
docs_dir: docs/
repo_name: 'AI4EPS/PhaseNet'
repo_url: 'https://github.com/ai4eps/PhaseNet'
nav:
    - Overview: README.md
    - Interactive Example: example_gradio.ipynb
    - Batch Prediction: example_batch_prediction.ipynb
theme:
  name: 'material'
plugins:
  - mkdocs-jupyter
extra:
  analytics:
    provider: google
    property: G-RZQ9LRPL0S
